import fs from "fs";

// @Description: Scrape the generated entities folder for all entities and return a map of entity names to entity paths
// @Params: src: string - the path to the entities folder generated by typeorm-model-generator (e.g. "./output/entities")

async function getEntityTable(src: string){
    let entities= <any>[];
    fs.readdirSync(src).forEach(file => entities.push(file));
    return entities;
}

export default getEntityTable;
